#version 460 core
#extension GL_EXT_ray_tracing : enable


struct CallableData {
    vec3 outColor;
    int geometryIndex;
};

layout(location = 0) callableDataInEXT CallableData data;

void main()
{
    // Generate a checker board pattern
	vec2 pos = vec2(gl_LaunchIDEXT / 8);
	if (data.geometryIndex > 0)
		data.outColor = vec3(mod(pos.x + mod(pos.y, 2.0), 2.0));
	else
		data.outColor = vec3(1.0, 0.0, 0.0);
}